Update target framework to .NET 7
Yaming-Hub/HttpTunnel pull request #17
Opened 2023-01-21 00:02 UTC by nordoff

Update NLog to 5.2.1

2023-01-23 18:54 UTC, Yaming-Hub requested changes

2023-01-23 18:54 UTC, Yaming-Hub commented on src/HttpTunnel/HttpTunnel.csproj
> +    <Version>1.0.2</Version>
Please change to 2.0.0 after we upgrade from .Net 5 to .Net 7. This is a major change and the previous setup may not work.

2023-01-23 19:07 UTC, snakefoot commented
Notice that [NLog v5 includes breaking changes](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlogextensionslogging-changes-capture-of-eventid). Ex. LogEvent-Property `EventId_id` +`EventId_Name` changing to `EventId` + `EventName`:

https://github.com/Yaming-Hub/HttpTunnel/blob/main/src/HttpTunnel/nlog.config
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="Info"
      internalLogToConsole="true">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- File Target for all log messages with basic details -->
    <target xsi:type="File" name="system" fileName="logs\system-${shortdate}.log"
            layout="${longdate}|${uppercase:${level}}|${logger}|${event-properties:item=EventName}|${message} ${exception:format=tostring}" />

    <!-- File Target for own log messages with extra web details using some ASP.NET core renderers -->
    <target xsi:type="File" name="request" fileName="logs\request-${shortdate}.log"
            layout="${longdate}|${uppercase:${level}}|${logger}|${event-properties:item=EventName}|${message}" />

    <!--Console Target for hosting lifetime messages to improve Docker / Visual Studio startup detection -->
    <target xsi:type="Console" name="console" layout="${level:truncate=4:tolower=true}\: ${logger}[0]${newline}      ${message}${exception:format=tostring}" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>

    <logger name="HttpTunnel.Implementations.*" minlevel="Info" writeTo="request" >
      <filters>
        <when condition="equals('${event-properties:item=EventName}','RequestReceived')" action="LogFinal" />
        <when condition="equals('${event-properties:item=EventName}','ResponseReturned')" action="LogFinal" />
        <when condition="equals('${event-properties:item=EventName}','RequestSent')" action="LogFinal" />
        <when condition="equals('${event-properties:item=EventName}','ResponseReceived')" action="LogFinal" />
      </filters>
    </logger>
    
    <logger name="*" minlevel="Trace" writeTo="system" />
    <logger name="*" minlevel="Trace" writeTo="console" />
  </rules>
</nlog>
```

2023-01-24 16:31 UTC, Yaming-Hub approved these changes

2023-01-25 17:43 UTC, merged